### ISSUE TITLE
.connect() takes a long time to join channels

### ISSUE THREAD

**Issue by walkah** [gf3/Jerk#8]
hacking together a bot for some internal use and jerk(function() {}).connect(options) connects (to freenode) quickly, but takes a very long time to join the channels listed in options['channels'] - making it not that fun to hack on.

I'm not sure if this is an issue in jerk or irc-js...

**Comment by gf3** [comment]
In order to function correctly on a wide variety of networks, Jerk, by default is set to join channels 15 seconds _after_ it receives a PING from the server. This prevents the bot from trying to join channels too soon, then failing to join them at all. To cut down this time, you can change the timeout in the options to something shorter like so `options.delayAfterConnect = 1`.

Relevant Jerk code: https://github.com/gf3/Jerk/blob/master/lib/jerk.js#L32-42

**Comment by gf3** [comment]
I should probably make this shorter by default though.

**Comment by walkah** [comment]
that's much better! thanks :-)
